spring:
  application:
    name: banking-transactions
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
  elasticsearch:
    uris: http://localhost:9200
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8000
  servlet:
    context-path: /api
jwt:
  secret: yLJ9Zf7x2N8qRM4WpTuViX6qZdCEpB3m
  expirationMillis: 3600000
cache:
  ttl-minutes: 10